version: '3.8'
services:
  customer_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  order_app:
    container_name: customer_service
    depends_on:
      - customer_db
    build: .
    environment:
      DB_HOST: customer_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    links:
      - customer_db
    ports:
      - '8000:8000'
    command: uvicorn app:app --host 0.0.0.0 --port 8000
volumes:
  db:
    driver: local
